name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |        
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
        run: |
          docker build -t jsantamv/docker-graphql:1.0.1 .
          
    - name: Push the Docker image
      run: |
        docker push jsantamv/docker-graphql:1.0.1
    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
