name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'src/**'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.2
      with:
        major_pattern: 'major:'
        minor_pattern: 'feat:'
        patch_pattern: 'fix:'
        no_bump_pattern: 'docs:|chore:|refactor:'
        format: "${major}.${minor}.${patch}${{ steps.version.outputs.increment != '' && '-rc.' || '' }}${{ steps.version.outputs.increment }}"
        tag_prefix: "v"
      id: version
      
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin

    - name: Build the Docker image
      run: |
        docker build -t jsantamv/docker-graphql:$NEW_VERSION .
        docker build -t jsantamv/docker-graphql:latest .

    - name: Push the Docker image
      run: |
        docker push jsantamv/docker-graphql:$NEW_VERSION
        docker push jsantamv/docker-graphql:latest
